const colors = require('tailwindcss/colors')

const grayScale = {
  white: '#FFFFFF',
  'off-white': '#FAFAFA',
  'gray-light': '#F5F5F5',
  'gray-light-mid': '#D8D8D8',
  'gray-mid': '#949494',
  'gray-mid-dark': '#6F6F6F',
  'gray-dark': '#222222',
  black: '#000000',
}

const socialColors = {
  facebook: '#3b5998',
  twitter: '#00acee',
  instagram: '#dd2a7b',
  youtube: '#FF0000',
}

const fallbackFontStack = [
  '-apple-system',
  'BlinkMacSystemFont',
  'San Francisco',
  'Segoe UI',
  'Roboto',
  'Helvetica Neue',
  'sans-serif',
  'Apple Color Emoji',
  'Segoe UI Emoji',
  'Segoe UI Symbol',
  'Noto Color Emoji',
]

module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx, mdx}"],
  mode: "jit",
  theme: {
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
      "3xl": "1800px",
      "4xl": "1900px",
      // Media queries to detect the user’s input modality real, non-simulated hover support.
      "can-hover": { raw: "(hover: hover)" },
      "no-hover": { raw: "(hover: none)" },
    },
    colors: {
      ...grayScale,
      ...socialColors,
      transparent: "transparent",
      current: 'currentColor',
      "warning": "var(--png-color_warning)",
      "warning-light": "var(--png-color_warning-light)",
      "warning-dark": "var(--png-color_warning-dark)",

      
      "background-primary": "var(--png-color_background-primary)",
      "background-secondary": "var(--png-color_background-secondary)",
      "background-brand-primary": "var(--png-color_background-brand-primary)",
      "background-brand-secondary": "var(--png-color_background-brand-secondary)",
      "background-accent": "var(--png-color_background-accent)",
      "background-alert": "var(--png-color_background-alert)",
      "content-primary": "var(--png-color_content-primary)",
      "content-secondary": "var(--png-color_content-secondary)",
      "content-action": "var(--png-color_content-action)",
      "content-active": "var(--png-color_content-active)",
      "content-inactive": "var(--png-color_content-inactive)",
      "content-negative": "var(--png-color_content-negative)",
      "content-warning": "var(--png-color_content-warning)",
      "content-positive": "var(--png-color_content-positive)",
      "content-information": "var(--png-color_content-information)",
      "content-accent": "var(--png-color_content-accent)",
      "content-visited": "var(--png-color_content-visited)",
      "border-primary": "var(--png-color_border-primary)",
      "border-secondary": "var(--png-color_border-secondary)",
      "border-active": "var(--png-color_border-active)",
      "border-inactive": "var(--png-color_border-inactive)",
      "border-negative": "var(--png-color_border-negative)",
      "border-warning": "var(--png-color_border-warning)",
      "border-positive": "var(--png-color_border-positive)",
      "border-information": "var(--png-color_border-information)",
      "hover-primary": "var(--png-color_hover-primary)",
      "hover-secondary": "var(--png-color_hover-secondary)",
      "hover-primary-transparent": "var(--png-color_hover-primary-transparent)",
      "hover-secondary-transparent": "var(--png-color_hover-secondary-transparent)",
      "hover-brand": "var(--png-color_hover-brand)",
      "hover-accent": "var(--png-color_hover-accent)",
      "active-primary": "var(--png-color_active-primary)",
      "active-primary-transparent": "var(--png-color_active-primary-transparent)",
      "active-secondary-transparent": "var(--png-color_active-secondary-transparent)",
      "active-tertiary": "var(--png-color_active-tertiary)",
      "active-tertiary-transparent": "var(--png-color_active-tertiary-transparent)",
      "active-brand": "var(--png-color_active-brand)",
      "active-accent": "var(--png-color_active-accent)",
      "active-primary-reversed-transparent": "var(--png-color_active-primary-reversed-transparent)",
      "active-secondary-reversed-transparent": "var(--png-color_active-secondary-reversed-transparent)",
      "active-brand-reversed-transparent": "var(--png-color_active-brand-reversed-transparent)",
      shadow: "var(--png-color_shadow)",
    },
    // spacing: {
    //   0: "var(--png-spacing_0)",
    //   1: "var(--png-spacing_1)",
    //   2: "var(--png-spacing_2)",
    //   3: "var(--png-spacing_3)",
    //   4: "var(--png-spacing_4)",
    //   5: "var(--png-spacing_5)",
    //   6: "var(--png-spacing_6)",
    //   7: "var(--png-spacing_7)",
    //   8: "var(--png-spacing_8)",
    //   9: "var(--png-spacing_9)",
    //   10: "var(--png-spacing_10)",
    // },
    fontFamily: {
      regular: ["Roboto", ...fallbackFontStack],
      condensed: ["Roboto Condensed", ...fallbackFontStack],
      display: ["Roboto Condensed", ...fallbackFontStack],
      body: ["Roboto", ...fallbackFontStack],
    },
    scale: {
      0: "0",
      50: ".5",
      75: ".75",
      90: ".9",
      95: ".95",
      100: "1",
      105: "1.05",
      110: "1.1",
      125: "1.25",
      150: "1.5",
    },
    checkbox: {
      display: "inline-block",
      verticalAlign: "top",
      flexShrink: 0,
      borderWidth: 0,
      borderRadius: 0,
    },
  },
  extend: {
    borderRadius: {
      100: "var(--png-radius_100)",
      200: "var(--png-radius_200)",
      300: "var(--png-radius_300)",
      400: "var(--png-radius_400)",
      500: "var(--png-radius_500)",
      600: "var(--png-radius_600)",
      700: "var(--png-radius_700)",
      800: "var(--png-radius_800)",
    },
    boxShadow: {
      100: "var(--png-shadow_100)",
      200: "var(--png-shadow_200)",
      300: "var(--png-shadow_300)",
      400: "var(--png-shadow_400)",
    },
    animation: {
      fadeIn: "fadeIn 500ms ease-in forwards",
      fadeOut: "fadeOut 500ms ease-out forwards",
      fadeInSlow: "fadeIn 1000ms ease-in forwards",
      fadeOutSlow: "fadeOut 1000ms ease-out forwards",
      scaleIn: "scaleIn 300ms ease-in forwards",
      rotate: "rotate 1s linear infinite",
    },
    keyframes: {
      fadeIn: {
        "0%": { opacity: 0 },
        "100%": { opacity: 1 },
      },
      fadeOut: {
        "100%": { opacity: 1 },
        "0%": { opacity: 0 },
      },
      scaleIn: {
        "0%": { transform: "scale(0)" },
        "100%": { transform: "scale(1)" },
      },
      rotate: {
        "100%": { transform: "rotate(360deg)" },
      },
    },
    minHeight: {
      none: "none",
      "1/4": "25%",
      "1/2": "50%",
      18: "4.5rem",
      28: "7rem",
      66: "16rem",
      100: "25rem",
    },
    opacity: {
      15: "0.15",
      30: "0.30",
      40: "0.40",
      90: "0.90",
      98: "0.98",
    },
    transitionDuration: {
      2000: "2000ms",
      2500: "2500ms",
      3000: "3000ms",
      3500: "3500ms",
      5000: "5000ms",
    },
  },
  variants: {
    textColor: ["responsive", "hover", "focus", "group-hover"],
    textDecoration: ["responsive", "hover", "focus", "group-hover"],
    textOpacity: ["hover", "group-hover"],
    backgroundColor: ["responsive", "hover", "focus", "group-hover"],
    transformOrigin: ["responsive", "hover"],
    translate: ["responsive", "hover", "focus", "group-hover"],
    transitionDelay: ["responsive", "group-hover"],
    opacity: ["responsive", "hover", "focus", "group-hover"],
    scale: ["responsive", "hover", "focus", "group-hover"],
    margin: ["responsive", "group-hover"],
    borderWidth: ["responsive", "hover", "focus", "group-hover"],
    borderColor: ["responsive", "hover", "focus", "group-hover"],
    animation: ["responsive", "motion-safe", "motion-reduce"],
  },
  plugins: [require("@tailwindcss/forms")],
};
